#
# For information on Gradle's TOML catalog file, see the following reference documentation:
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format
#

[versions]

[libraries]
